name: medhive_proj
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase dependencies - use latest compatible versions
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  firebase_database: ^12.0.0
  cloud_firestore: ^6.0.0

  # Add other dependencies here

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/